name: Compiler Linux Kernel
on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:
    inputs:
      KERNEL_VERSION:
        required: true
        description: "CHOSE OUR KERNEL VERSION:"
        type: choice
        default: latest
        options:
          - latest
          - 6.9-rc5
          - 6.8.7
          - 6.7.12
          - 6.6.28
          - 6.1.87
          - 5.15.156
          - 5.10.215
          - 5.4.274
          - 4.19.312
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        defconfig: [tinyconfig]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make build-essential libncurses-dev wget curl tar bison flex libssl-dev grep sed libelf1
          
      - name: Download and extract latest kernel
        id: download_kernel
        run: |
          if [ ${{ github.event.inputs.KERNEL_VERSION }} == "latest" ];then
            latest_version=$(curl -s https://www.kernel.org/finger_banner | grep -m1 "$1" | sed -r 's/^.+: +([^ ]+)( .+)?$/\1/')
          else
            latest_version=${{ github.event.inputs.KERNEL_VERSION }}
          fi
          if [ ! -f linux-${latest_version}.tar.xz ];then
            wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${latest_version}.tar.xz
          fi
          if [ ! -d linux-${latest_version} ];then
            tar -xvf linux-${latest_version}.tar.xz
          fi
          echo "LATEST_VERSION=${latest_version}" >> $GITHUB_ENV
          echo done! linux-${latest_version}
          
      #- name: Cache ccache
      #  uses: actions/cache@v2
      #  with:
      #    path: ~/.ccache
      #    key: ${{ matrix.defconfig }}

            
      - name: Building Kernel
        run: |
            echo linux-${{ env.LATEST_VERSION }}
            ls
            cd linux-${{ env.LATEST_VERSION }}
            export CFLAGS="-march=silvermont -mtune=silvermont -m3dnow -m3dnowa -mfpmath=sse -Os"
            export CXXFLAGS="-march=silvermont -mtune=silvermont -m3dnow -m3dnowa -mfpmath=sse -Os"
            # Build only minimal debug info to reduce size
            CFLAGS+=' -g1'
            CXXFLAGS+=' -g1'
            make ${{ matrix.defconfig }}
            make -j$(nproc)
    
      - name: Upload Kernel Linux Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Kernel Linux Image
          path: linux-${{ env.LATEST_VERSION }}/arch/x86/boot/bzImage
